/*
==========================================================================================
DỰ ÁN: QUẢN LÝ THÚ CƯNG (PetCareX)
HỆ QUẢN TRỊ: MS SQL SERVER

MỤC LỤC (TABLE OF CONTENTS):
------------------------------------------------------------------------------------------
   PHẦN 1: KHỞI TẠO DATABASE (DATABASE INITIALIZATION)
           - Xóa DB cũ nếu tồn tại
           - Tạo DB mới

   PHẦN 2: ĐỊNH NGHĨA BẢNG (TABLE DEFINITIONS)
           - Khai báo tên cột và kiểu dữ liệu
           - NOT NULL constraints

   PHẦN 3: RÀNG BUỘC NỘI TẠI (INTERNAL CONSTRAINTS)
           - Primary Keys (PK)
           - Check Constraints (CK)
           - Unique Constraints (UQ)
           - Default Constraints (DF)

   PHẦN 4: RÀNG BUỘC QUAN HỆ (FOREIGN KEYS)
           - Thiết lập quan hệ giữa các bảng (FK)
==========================================================================================
*/

-- =======================================================================================
-- PHẦN 1: KHỞI TẠO DATABASE
-- =======================================================================================
USE master;
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = N'PetCareX')
BEGIN
    ALTER DATABASE PetCareX SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE PetCareX;
END
GO

CREATE DATABASE PetCareX;
GO

USE PetCareX;
GO

-- Khởi tạo database thứ hai giống hệt với cái ban đầu để test cài đặt giải pháp
/*USE master;
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = N'PetCareX_Optimized')
BEGIN
    ALTER DATABASE PetCareX_Optimized SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE PetCareX_Optimized;
END
GO

CREATE DATABASE PetCareX_Optimized;
GO

USE PetCareX_Optimized;
GO*/

-- =======================================================================================
-- PHẦN 2: ĐỊNH NGHĨA BẢNG (TABLE DEFINITIONS)
-- =======================================================================================

-- 1. Bảng Cấp thành viên
CREATE TABLE CAPTHANHVIEN (
    CapTV           NVARCHAR(10)   NOT NULL,
    ChiTieuToiThieu DECIMAL(18, 0) NOT NULL,
    ChiTieuGiuHang  DECIMAL(18, 0) NOT NULL
);

-- 2. Bảng Chi nhánh
CREATE TABLE CHINHANH (
    MaCN            CHAR(10)      NOT NULL,
    TenCN           NVARCHAR(100) NOT NULL,
    DiaChi          NVARCHAR(100) NOT NULL,
    SDTCN           VARCHAR(10)   NOT NULL,
    ThoiGianMoCua   TIME          NOT NULL,
    ThoiGianDongCua TIME          NOT NULL,
);

-- 3. Bảng Dịch vụ
CREATE TABLE DICHVU (
    MaDV  CHAR(10)       NOT NULL,
    TenDV NVARCHAR(100)  NOT NULL,
    PhiDV DECIMAL(18, 0) NOT NULL
);

-- 4. Bảng trung gian Chi nhánh - Dịch vụ
CREATE TABLE CHINHANH_DICHVU (
    MaCN CHAR(10) NOT NULL,
    MaDV CHAR(10) NOT NULL,
);

-- 5. Bảng Gói tiêm
CREATE TABLE GOITIEM (
    MaGT       CHAR(10) NOT NULL,
    ThoiGianGT INT      NOT NULL,
    UuDai      FLOAT    NOT NULL
);

-- 6. Bảng Sản phẩm (Cha của Thuốc và Vacxin)
CREATE TABLE SANPHAM (
    MaSP      CHAR(10)       NOT NULL,
    TenSP     NVARCHAR(100)  NOT NULL,
    LoaiSP    CHAR(1)        NOT NULL, -- 'H', 'T', 'V'
    DonViTinh NVARCHAR(20)   NOT NULL,
    Gia       DECIMAL(18, 0) NOT NULL,
    SLTonKho  INT            NOT NULL
);

-- 7. Bảng Thuốc (Kế thừa Sản phẩm)
CREATE TABLE THUOC (
    TMaSP     CHAR(10)     NOT NULL,
    LoaiThuoc NVARCHAR(50) NOT NULL,
    NSX       DATE         NOT NULL,
    HSD       DATE         NOT NULL,
    NhaSX     NVARCHAR(50) NOT NULL
);

-- 8. Bảng Vacxin (Kế thừa Sản phẩm)
CREATE TABLE VACXIN (
    VMaSP      CHAR(10)     NOT NULL,
    LoaiVacXin NVARCHAR(50) NOT NULL,
    NSX        DATE         NOT NULL,
    HSD        DATE         NOT NULL,
    NhaSX      NVARCHAR(50) NOT NULL
);

-- 9. Bảng Nhân viên
CREATE TABLE NHANVIEN (
    MaNV        CHAR(10)     NOT NULL,
    HoTenNV     NVARCHAR(50) NOT NULL,
    NgaySinhNV  DATE         NOT NULL,
    GioiTinhNV  NVARCHAR(10) NOT NULL,
    TrangThaiLV NVARCHAR(50), 
    LoaiNV      CHAR(1)      NOT NULL -- 'B', 'T', 'H', 'Q'
);

-- 10. Bảng Bác sĩ thú y (Kế thừa Nhân viên)
CREATE TABLE BACSITHUY (
    BMaNV            CHAR(10)     NOT NULL,
    ChungChiHanhNghe VARCHAR(50)  NOT NULL,
    ChuyenKhoa       NVARCHAR(50) NOT NULL,
    SoNamKinhNghiem  INT          NOT NULL
);

-- 11. Bảng Nhân viên tiếp tân (Kế thừa Nhân viên)
CREATE TABLE NHANVIENTIEPTAN (
    TMaNV        CHAR(10)     NOT NULL,
    QuayTiepNhan NVARCHAR(20) NOT NULL
);

-- 12. Bảng Nhân viên bán hàng (Kế thừa Nhân viên)
CREATE TABLE NHANVIENBANHANG (
    HMaNV     CHAR(10)     NOT NULL,
    CaLamViec NVARCHAR(20) NOT NULL
);

-- 13. Bảng Nhân viên quản lý (Kế thừa Nhân viên)
CREATE TABLE NHANVIENQUANLY (
    QMaNV   CHAR(10)       NOT NULL,
    BangCap NVARCHAR(50)   NOT NULL,
    PhuCap  DECIMAL(18, 0) NOT NULL
);

-- 14. Bảng Lịch sử công tác
CREATE TABLE LICHSUCONGTAC (
    MaNV       CHAR(10)       NOT NULL,
    MaCN       CHAR(10)       NOT NULL,
    NgayVaoLam DATE           NOT NULL,
    NgayChuyen DATE               NULL,
    ChucVu     NVARCHAR(50)   NOT NULL,
    LuongCoBan DECIMAL(18, 0) NOT NULL
);

-- 15. Bảng Khách hàng
CREATE TABLE KHACHHANG (
    MaKH        CHAR(10)     NOT NULL,
    HoTenKH     NVARCHAR(50) NOT NULL,
    SDTKH       VARCHAR(10)  NOT NULL,
    EmailKH     VARCHAR(50)  NOT NULL,
    CCCD        VARCHAR(12)  NOT NULL,
    GioiTinhKH  NVARCHAR(10) NOT NULL,
    NgaySinhKH  DATE         NOT NULL,
    DiemLoyalty INT          NOT NULL,
    CapTV       NVARCHAR(10) NOT NULL,
    NgayDatCap  DATE         NOT NULL
);

-- 16. Bảng Tài khoản hội viên
CREATE TABLE TAIKHOANHOIVIEN (
    MaKH        CHAR(10)     NOT NULL,
    TenDangNhap VARCHAR(50)  NOT NULL,
    MatKhau     VARCHAR(255) NOT NULL,
    NgayDangKy  DATETIME     NOT NULL
);

-- 17. Bảng Thú cưng
CREATE TABLE THUCUNG (
    MaTC             CHAR(10)      NOT NULL,
    TenTC            NVARCHAR(50)  NOT NULL,
    Loai             NVARCHAR(10)  NOT NULL,
    Giong            NVARCHAR(50)  NOT NULL,
    NgaySinhTC       DATE          NOT NULL,
    GioiTinhTC       NVARCHAR(10)  NOT NULL,
    TinhTrangSucKhoe NVARCHAR(100) NOT NULL,
    MaKH             CHAR(10)      NOT NULL
);

-- 18. Bảng Phiếu đặt
CREATE TABLE PHIEUDAT (
    MaKH           CHAR(10)     NOT NULL,
    MaTC           CHAR(10)     NOT NULL,
    ThoiGianDat    DATETIME     NOT NULL,
    ThoiGianHen    DATETIME     NOT NULL,
    LoaiHinhDichVu NVARCHAR(50) NOT NULL,
    TrangThaiPD    NVARCHAR(20) NOT NULL,
    STT            INT          NOT NULL,
    MaCN           CHAR(10)     NOT NULL
);

-- 19. Bảng Lịch sử dịch vụ
CREATE TABLE LICHSUDICHVU (
    MaGD CHAR(25) NOT NULL,
    MaDV CHAR(10) NOT NULL
);

-- 20. Bảng Hóa đơn
CREATE TABLE HOADON (
    MaHD          CHAR(25)       NOT NULL,
    ThoiGianLapHD DATETIME       NOT NULL,
    KhuyenMai     DECIMAL(18, 0) NOT NULL,
    TongTien      DECIMAL(18, 0) NOT NULL,
    MaTC          CHAR(10)       NULL,
    HMaNV         CHAR(10)       NULL
);

-- 21. Bảng Chi tiết hóa đơn
CREATE TABLE CHITIETHOADON (
    MaHD      CHAR(25)       NOT NULL,
    STT       INT            NOT NULL,
    SoLuong   INT            NOT NULL,
    DonGia    DECIMAL(18, 0) NOT NULL,
    ThanhTien DECIMAL(18, 0) NOT NULL,
    MaGD      CHAR(25)       NULL,
    MaSP      CHAR(10)       NULL
);

-- 22. Bảng Thông tin thanh toán
CREATE TABLE THONGTINTHANHTOAN (
    MaKH         CHAR(10)     NOT NULL,
    MaHD         CHAR(25)     NOT NULL,
    PhuongThucTT NVARCHAR(50) NOT NULL,
    ThoiGianTT   DATETIME     NOT NULL,
    TrangThaiTT  NVARCHAR(50) NOT NULL
);

-- 23. Bảng Đánh giá
CREATE TABLE DANHGIA (
    MaHD          CHAR(25)      NOT NULL,
    MaKH          CHAR(10)      NOT NULL,
    DiemChatLuong INT           NOT NULL,
    ThaiDoNV      NVARCHAR(50)  NOT NULL,
    MucDoHaiLong  NVARCHAR(50)  NOT NULL,
    BinhLuan      NVARCHAR(200)     NULL
);

-- 24. Bảng Khám bệnh
CREATE TABLE KHAMBENH (
    KMaGD       CHAR(25)      NOT NULL,
    TrieuChung  NVARCHAR(200) NOT NULL,
    ChanDoan    NVARCHAR(200) NOT NULL,
    NgayKham    DATE          NOT NULL,
    NgayTaiKham DATE              NULL,
    BMaNV       CHAR(10)      NOT NULL
);

-- 25. Bảng Tiêm phòng
CREATE TABLE TIEMPHONG (
    TMaGD         CHAR(25)     NOT NULL,
    ThoiGianTiem  DATETIME     NOT NULL,
    LieuLuongTiem FLOAT        NOT NULL,
    LoaiHinhTiem  NVARCHAR(50) NOT NULL,
    MaGT          CHAR(10)         NULL,
    VMaSP         CHAR(10)     NOT NULL,
    BMaNV         CHAR(10)     NOT NULL
);

-- 26. Bảng Toa thuốc
CREATE TABLE TOATHUOC (
    MaTT          CHAR(25) NOT NULL,
    ThoiGianLapTT DATETIME NOT NULL,
    KMaGD         CHAR(25) NOT NULL
);

-- 27. Bảng Chi tiết toa thuốc
CREATE TABLE CHITIETTOATHUOC (
    MaTT         CHAR(25)      NOT NULL,
    TMaSP        CHAR(10)      NOT NULL,
    HuongDan     NVARCHAR(200) NOT NULL,
    SoLuongThuoc INT           NOT NULL,
    LieuDung     NVARCHAR(100) NOT NULL
);
GO

-- =======================================================================================
-- PHẦN 3: RÀNG BUỘC NỘI TẠI (PK, CHECK, UNIQUE, DEFAULT)
-- =======================================================================================

-- CAPTHANHVIEN
ALTER TABLE CAPTHANHVIEN ADD CONSTRAINT PK_CAPTHANHVIEN_CapTV PRIMARY KEY (CapTV);
ALTER TABLE CAPTHANHVIEN ADD CONSTRAINT CK_CAPTHANHVIEN_ChiTieuToiThieu CHECK (ChiTieuToiThieu >= 0);
ALTER TABLE CAPTHANHVIEN ADD CONSTRAINT CK_CAPTHANHVIEN_ChiTieuGiuHang CHECK (ChiTieuGiuHang >= 0);
ALTER TABLE CAPTHANHVIEN ADD CONSTRAINT CK_CAPTHANHVIEN_CapTV CHECK (CapTV IN ('Cơ bản', 'Thân thiết', 'VIP'));

-- CHINHANH
ALTER TABLE CHINHANH ADD CONSTRAINT PK_CHINHANH_MaCN PRIMARY KEY (MaCN);
ALTER TABLE CHINHANH ADD CONSTRAINT UQ_CHINHANH_DiaChi UNIQUE (DiaChi);
ALTER TABLE CHINHANH ADD CONSTRAINT UQ_CHINHANH_SDTCN UNIQUE (SDTCN);
ALTER TABLE CHINHANH ADD CONSTRAINT CK_CHINHANH_ThoiGianMoCua_ThoiGianDongCua CHECK (ThoiGianMoCua < ThoiGianDongCua);

-- DICHVU
ALTER TABLE DICHVU ADD CONSTRAINT PK_DICHVU_MaDV PRIMARY KEY (MaDV);
ALTER TABLE DICHVU ADD CONSTRAINT CK_DICHVU_PhiDV CHECK (PhiDV >= 0);

-- CHINHANH_DICHVU (Bảng trung gian)
ALTER TABLE CHINHANH_DICHVU ADD CONSTRAINT PK_CHINHANH_DICHVU_MaCN_MaDV PRIMARY KEY (MaCN, MaDV);

-- GOITIEM
ALTER TABLE GOITIEM ADD CONSTRAINT PK_GOITIEM_MaGT PRIMARY KEY (MaGT);
ALTER TABLE GOITIEM ADD CONSTRAINT CK_GOITIEM_ThoiGianGT CHECK (ThoiGianGT > 0);
ALTER TABLE GOITIEM ADD CONSTRAINT CK_GOITIEM_UuDai CHECK (UuDai BETWEEN 0.05 AND 0.15);

-- SANPHAM
ALTER TABLE SANPHAM ADD CONSTRAINT PK_SANPHAM_MaSP PRIMARY KEY (MaSP);
ALTER TABLE SANPHAM ADD CONSTRAINT CK_SANPHAM_LoaiSP CHECK (LoaiSP IN ('H', 'T', 'V'));
ALTER TABLE SANPHAM ADD CONSTRAINT CK_SANPHAM_Gia CHECK (Gia > 0);
ALTER TABLE SANPHAM ADD CONSTRAINT CK_SANPHAM_SLTonKho CHECK (SLTonKho >= 0);

-- THUOC
ALTER TABLE THUOC ADD CONSTRAINT PK_THUOC_TMaSP PRIMARY KEY (TMaSP);
ALTER TABLE THUOC ADD CONSTRAINT CK_THUOC_NSX_HSD CHECK (NSX < HSD);

-- VACXIN
ALTER TABLE VACXIN ADD CONSTRAINT PK_VACXIN_VMaSP PRIMARY KEY (VMaSP);
ALTER TABLE VACXIN ADD CONSTRAINT CK_VACXIN_NSX_HSD CHECK (NSX < HSD);

-- NHANVIEN
ALTER TABLE NHANVIEN ADD CONSTRAINT PK_NHANVIEN_MaNV PRIMARY KEY (MaNV);
ALTER TABLE NHANVIEN ADD CONSTRAINT CK_NHANVIEN_GioiTinh CHECK (GioiTinhNV IN (N'Nam', N'Nữ'));
ALTER TABLE NHANVIEN ADD CONSTRAINT CK_NHANVIEN_LoaiNV CHECK (LoaiNV IN ('B', 'T', 'H', 'Q'));
ALTER TABLE NHANVIEN ADD CONSTRAINT DF_NHANVIEN_TrangThaiLV DEFAULT N'Đang làm việc' FOR TrangThaiLV;

-- BACSITHUY
ALTER TABLE BACSITHUY ADD CONSTRAINT PK_BACSITHUY_BMaNV PRIMARY KEY (BMaNV);
ALTER TABLE BACSITHUY ADD CONSTRAINT CK_BACSITHUY_SoNamKinhNghiem CHECK (SoNamKinhNghiem >= 1);

-- NHANVIENTIEPTAN & BANHANG & QUANLY
ALTER TABLE NHANVIENTIEPTAN ADD CONSTRAINT PK_NHANVIENTIEPTAN_TMaNV PRIMARY KEY (TMaNV);
ALTER TABLE NHANVIENBANHANG ADD CONSTRAINT PK_NHANVIENBANHANG_HMaNV PRIMARY KEY (HMaNV);
ALTER TABLE NHANVIENQUANLY ADD CONSTRAINT PK_NHANVIENQUANLY_QMaNV PRIMARY KEY (QMaNV);
ALTER TABLE NHANVIENQUANLY ADD CONSTRAINT CK_NHANVIENQUANLY_PhuCap CHECK (PhuCap > 0);

-- LICHSUCONGTAC
ALTER TABLE LICHSUCONGTAC ADD CONSTRAINT PK_LICHSUCONGTAC_MaNV_MaCN_NgayVaoLam PRIMARY KEY (MaNV, MaCN, NgayVaoLam);
ALTER TABLE LICHSUCONGTAC ADD CONSTRAINT CK_LICHSUCONGTAC_NgayVaoLam_NgayChuyen CHECK (NgayVaoLam <= NgayChuyen);
ALTER TABLE LICHSUCONGTAC ADD CONSTRAINT CK_LICHSUCONGTAC_LuongCoban CHECK (LuongCoBan > 0);

-- KHACHHANG
ALTER TABLE KHACHHANG ADD CONSTRAINT PK_KHACHHANG_MaKH PRIMARY KEY (MaKH);
ALTER TABLE KHACHHANG ADD CONSTRAINT UQ_KHACHHANG_STDKH UNIQUE (SDTKH);
ALTER TABLE KHACHHANG ADD CONSTRAINT UQ_KHACHHANG_EmailKH UNIQUE (EmailKH);
ALTER TABLE KHACHHANG ADD CONSTRAINT UQ_KHACHHANG_CCCD UNIQUE (CCCD);
ALTER TABLE KHACHHANG ADD CONSTRAINT CK_KHACHHANG_GioiTinhKH CHECK (GioiTinhKH IN (N'Nam', N'Nữ'));
ALTER TABLE KHACHHANG ADD CONSTRAINT CK_KHACHHANG_DiemLoyalty CHECK (DiemLoyalty >= 0);
ALTER TABLE KHACHHANG ADD CONSTRAINT CK_KHACHHANG_NgaySinhKH_NgayDatCap CHECK (NgaySinhKH < NgayDatCap);

-- TAIKHOANHOIVIEN
ALTER TABLE TAIKHOANHOIVIEN ADD CONSTRAINT PK_TAIKHOANHOIVIEN_MaKH PRIMARY KEY (MaKH);
ALTER TABLE TAIKHOANHOIVIEN ADD CONSTRAINT UQ_TAIKHOANHOIVIEN_TenDangNhap UNIQUE (TenDangNhap);

-- THUCUNG
ALTER TABLE THUCUNG ADD CONSTRAINT PK_THUCUNG_MaTC PRIMARY KEY (MaTC);
ALTER TABLE THUCUNG ADD CONSTRAINT CK_THUCUNG_GioiTinhTC CHECK (GioiTinhTC IN (N'Đực', N'Cái'));
ALTER TABLE THUCUNG ADD CONSTRAINT CK_THUCUNG_TinhTrangSucKhoe CHECK (TinhTrangSucKhoe IN (N'Rất tệ', N'Tệ', N'Bình thường', N'Tốt', N'Rất tốt'));

-- PHIEUDAT
ALTER TABLE PHIEUDAT ADD CONSTRAINT PK_PHIEUDAT_MaKH_MaTC_ThoiGianDat PRIMARY KEY (MaKH, MaTC, ThoiGianDat);
ALTER TABLE PHIEUDAT ADD CONSTRAINT CK_PHIEUDAT_ThoiGianDat_ThoiGianHen CHECK (ThoiGianDat < ThoiGianHen);
ALTER TABLE PHIEUDAT ADD CONSTRAINT CK_PHIEUDAT_LoaiHinhDichVu CHECK (LoaiHinhDichVu IN (N'Khám bệnh', N'Tiêm phòng'));
ALTER TABLE PHIEUDAT ADD CONSTRAINT DF_PHIEUDAT_TrangThaiPD DEFAULT N'Đã đặt' FOR TrangThaiPD;
ALTER TABLE PHIEUDAT ADD CONSTRAINT CK_PHIEUDAT_TrangThaiPD CHECK (TrangThaiPD IN (N'Đã đặt', N'Đã duyệt', N'Đã hủy', N'Hết hạn', N'Đã xong'));
ALTER TABLE PHIEUDAT ADD CONSTRAINT CK_PHIEUDAT_STT CHECK (STT > 0);

-- LICHSUDICHVU
ALTER TABLE LICHSUDICHVU ADD CONSTRAINT PK_LICHSUDICHVU_MaGD PRIMARY KEY (MaGD);

-- HOADON
ALTER TABLE HOADON ADD CONSTRAINT PK_HOADON_MaHD PRIMARY KEY (MaHD);
ALTER TABLE HOADON ADD CONSTRAINT CK_HOADON_KhuyenMai CHECK (KhuyenMai >= 0);
ALTER TABLE HOADON ADD CONSTRAINT CK_HOADON_TongTien CHECK (TongTien > 0);
ALTER TABLE HOADON ADD CONSTRAINT DF_HOADON_TongTien DEFAULT 0 FOR TongTien;

-- CHITIETHOADON
ALTER TABLE CHITIETHOADON ADD CONSTRAINT PK_CHITIETHOADON_MaHD_STT PRIMARY KEY (MaHD, STT);
ALTER TABLE CHITIETHOADON ADD CONSTRAINT CK_CHITIETHOADON_SoLuong CHECK (SoLuong > 0);
ALTER TABLE CHITIETHOADON ADD CONSTRAINT CK_CHITIETHOADON_DonGia CHECK (DonGia > 0);

-- THONGTINTHANHTOAN
ALTER TABLE THONGTINTHANHTOAN ADD CONSTRAINT PK_THONGTINTHANHTOAN_MaHD PRIMARY KEY (MaHD);
ALTER TABLE THONGTINTHANHTOAN ADD CONSTRAINT CK_THONGTINTHANHTOAN_PhuongThucTT CHECK (PhuongThucTT IN (N'Tiền mặt', N'Chuyển khoản'));
ALTER TABLE THONGTINTHANHTOAN ADD CONSTRAINT CK_THONGTINTHANHTOAN_TrangThaiTT CHECK (TrangThaiTT IN (N'Đang xử lý', N'Đã thanh toán', N'Chưa thanh toán'));

-- DANHGIA
ALTER TABLE DANHGIA ADD CONSTRAINT PK_DANHGIA_MaHD PRIMARY KEY (MaHD);
ALTER TABLE DANHGIA ADD CONSTRAINT CK_DANHGIA_DiemChatLuong CHECK (DiemChatLuong BETWEEN 1 AND 5);
ALTER TABLE DANHGIA ADD CONSTRAINT CK_DANHGIA_ThaiDoNV CHECK (ThaiDoNV IN (N'Rất tệ', N'Tệ', N'Bình thường', N'Tốt', N'Rất tốt'));
ALTER TABLE DANHGIA ADD CONSTRAINT CK_DANHGIA_MucDoHaiLong CHECK (MucDoHaiLong IN (N'Rất không hài lòng', N'Không hài lòng', N'Bình thường', N'Hài lòng', N'Rất hài lòng'));

-- KHAMBENH
ALTER TABLE KHAMBENH ADD CONSTRAINT PK_KHAMBENH_KMaGD PRIMARY KEY (KMaGD);
ALTER TABLE KHAMBENH ADD CONSTRAINT CK_KHAMBENH_NgayKham_NgayTaiKham CHECK (NgayKham < NgayTaiKham);

-- TIEMPHONG
ALTER TABLE TIEMPHONG ADD CONSTRAINT PK_TIEMPHONG_TMaGD PRIMARY KEY (TMaGD);

-- TOATHUOC
ALTER TABLE TOATHUOC ADD CONSTRAINT PK_TOATHUOC_MaTT PRIMARY KEY (MaTT);

-- CHITIETTOATHUOC
ALTER TABLE CHITIETTOATHUOC ADD CONSTRAINT PK_CHITIETTOATHUOC_MaTT_TMaSP PRIMARY KEY (MaTT, TMaSP);
ALTER TABLE CHITIETTOATHUOC ADD CONSTRAINT CK_CHITIETTOATHUOC_SoLuongThuoc CHECK (SoLuongThuoc > 0);
GO

-- =======================================================================================
-- PHẦN 4: RÀNG BUỘC QUAN HỆ (FOREIGN KEYS)
-- =======================================================================================

-- 1. CHINHANH_DICHVU -> CHINHANH
ALTER TABLE CHINHANH_DICHVU
ADD CONSTRAINT FK_CHINHANH_DICHVU_CHINHANH
FOREIGN KEY (MaCN) REFERENCES CHINHANH(MaCN)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 2. CHINHANH_DICHVU -> DICHVU
ALTER TABLE CHINHANH_DICHVU
ADD CONSTRAINT FK_CHINHANH_DICHVU_DICHVU
FOREIGN KEY (MaDV) REFERENCES DICHVU(MaDV)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 3. THUOC -> SANPHAM
ALTER TABLE THUOC
ADD CONSTRAINT FK_THUOC_SANPHAM
FOREIGN KEY (TMaSP) REFERENCES SANPHAM(MaSP)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 4. VACXIN -> SANPHAM
ALTER TABLE VACXIN
ADD CONSTRAINT FK_VACXIN_SANPHAM
FOREIGN KEY (VMaSP) REFERENCES SANPHAM(MaSP)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 5. BACSITHUY -> NHANVIEN
ALTER TABLE BACSITHUY
ADD CONSTRAINT FK_BACSITHUY_NHANVIEN
FOREIGN KEY (BMaNV) REFERENCES NHANVIEN(MaNV)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 6. NHANVIENTIEPTAN -> NHANVIEN
ALTER TABLE NHANVIENTIEPTAN
ADD CONSTRAINT FK_NHANVIENTIEPTAN_NHANVIEN
FOREIGN KEY (TMaNV) REFERENCES NHANVIEN(MaNV)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 7. NHANVIENBANHANG -> NHANVIEN
ALTER TABLE NHANVIENBANHANG
ADD CONSTRAINT FK_NHANVIENBANHANG_NHANVIEN
FOREIGN KEY (HMaNV) REFERENCES NHANVIEN(MaNV)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 8. NHANVIENQUANLY -> NHANVIEN
ALTER TABLE NHANVIENQUANLY
ADD CONSTRAINT FK_NHANVIENQUANLY_NHANVIEN
FOREIGN KEY (QMaNV) REFERENCES NHANVIEN(MaNV)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 9. LICHSUCONGTAC -> NHANVIEN
ALTER TABLE LICHSUCONGTAC
ADD CONSTRAINT FK_LICHSUCONGTAC_NHANVIEN
FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 10. LICHSUCONGTAC -> CHINHANH
ALTER TABLE LICHSUCONGTAC
ADD CONSTRAINT FK_LICHSUCONGTAC_CHINHANH
FOREIGN KEY (MaCN) REFERENCES CHINHANH(MaCN)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 11. KHACHHANG -> CAPTHANHVIEN
ALTER TABLE KHACHHANG
ADD CONSTRAINT FK_KHACHHANG_CAPTHANHVIEN
FOREIGN KEY (CapTV) REFERENCES CAPTHANHVIEN(CapTV)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 12. TAIKHOANHOIVIEN -> KHACHHANG
ALTER TABLE TAIKHOANHOIVIEN
ADD CONSTRAINT FK_TAIKHOANHOIVIEN_KHACHHANG
FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 13. THUCUNG -> KHACHHANG
ALTER TABLE THUCUNG
ADD CONSTRAINT FK_THUCUNG_KHACHHANG
FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 14. PHIEUDAT -> KHACHHANG
ALTER TABLE PHIEUDAT
ADD CONSTRAINT FK_PHIEUDAT_KHACHHANG
FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 15. PHIEUDAT -> THUCUNG
ALTER TABLE PHIEUDAT
ADD CONSTRAINT FK_PHIEUDAT_THUCUNG
FOREIGN KEY (MaTC) REFERENCES THUCUNG(MaTC)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 16. PHIEUDAT -> CHINHANH
ALTER TABLE PHIEUDAT
ADD CONSTRAINT FK_PHIEUDAT_CHINHANH
FOREIGN KEY (MaCN) REFERENCES CHINHANH(MaCN)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 17. LICHSUDICHVU -> DICHVU
ALTER TABLE LICHSUDICHVU
ADD CONSTRAINT FK_LICHSUDICHVU_DICHVU
FOREIGN KEY (MaDV) REFERENCES DICHVU(MaDV)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 18. HOADON -> THUCUNG
ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_THUCUNG
FOREIGN KEY (MaTC) REFERENCES THUCUNG(MaTC)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 19. HOADON -> NHANVIENBANHANG
ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_NHANVIENBANHANG
FOREIGN KEY (HMaNV) REFERENCES NHANVIENBANHANG(HMaNV)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 20. CHITIETHOADON -> HOADON
ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_CHITIETHOADON_HOADON
FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 21. CHITIETHOADON -> LICHSUDICHVU
ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_CHITIETHOADON_LICHSUDICHVU
FOREIGN KEY (MaGD) REFERENCES LICHSUDICHVU(MaGD)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 22. CHITIETHOADON -> SANPHAM
ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_CHITIETHOADON_SANPHAM
FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 23. THONGTINTHANHTOAN -> KHACHHANG
ALTER TABLE THONGTINTHANHTOAN
ADD CONSTRAINT FK_THONGTINTHANHTOAN_KHACHHANG
FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 24. THONGTINTHANHTOAN -> HOADON
ALTER TABLE THONGTINTHANHTOAN
ADD CONSTRAINT FK_THONGTINTHANHTOAN_HOADON
FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 25. DANHGIA -> HOADON
ALTER TABLE DANHGIA
ADD CONSTRAINT FK_DANHGIA_HOADON
FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 26. DANHGIA -> KHACHHANG
ALTER TABLE DANHGIA
ADD CONSTRAINT FK_DANHGIA_KHACHHANG
FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 27. KHAMBENH -> LICHSUDICHVU
ALTER TABLE KHAMBENH
ADD CONSTRAINT FK_KHAMBENH_LICHSUDICHVU
FOREIGN KEY (KMaGD) REFERENCES LICHSUDICHVU(MaGD)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 28. KHAMBENH -> BACSITHUY
ALTER TABLE KHAMBENH
ADD CONSTRAINT FK_KHAMBENH_BACSITHUY
FOREIGN KEY (BMaNV) REFERENCES BACSITHUY(BMaNV)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 29. TIEMPHONG -> LICHSUDICHVU
ALTER TABLE TIEMPHONG
ADD CONSTRAINT FK_TIEMPHONG_LICHSUDICHVU
FOREIGN KEY (TMaGD) REFERENCES LICHSUDICHVU(MaGD)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 30. TIEMPHONG -> GOITIEM
ALTER TABLE TIEMPHONG
ADD CONSTRAINT FK_TIEMPHONG_GOITIEM
FOREIGN KEY (MaGT) REFERENCES GOITIEM(MaGT)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 31. TIEMPHONG -> VACXIN
ALTER TABLE TIEMPHONG
ADD CONSTRAINT FK_TIEMPHONG_VACXIN
FOREIGN KEY (VMaSP) REFERENCES VACXIN(VMaSP)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 32. TIEMPHONG -> BACSITHUY
ALTER TABLE TIEMPHONG
ADD CONSTRAINT FK_TIEMPHONG_BACSITHUY
FOREIGN KEY (BMaNV) REFERENCES BACSITHUY(BMaNV)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 33. TOATHUOC -> KHAMBENH
ALTER TABLE TOATHUOC
ADD CONSTRAINT FK_TOATHUOC_KHAMBENH
FOREIGN KEY (KMaGD) REFERENCES KHAMBENH(KMaGD)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- 34. CHITIETTOATHUOC -> THUOC

ALTER TABLE CHITIETTOATHUOC
ADD CONSTRAINT FK_CHITIETTOATHUOC_TOATHUOC
FOREIGN KEY (MaTT) REFERENCES TOATHUOC(MaTT)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE CHITIETTOATHUOC
ADD CONSTRAINT FK_CHITIETTOATHUOC_THUOC
FOREIGN KEY (TMaSP) REFERENCES THUOC(TMaSP)
ON DELETE NO ACTION
ON UPDATE NO ACTION;
GO

USE master;
GO
SELECT name, physical_name 
FROM sys.master_files 
WHERE database_id = DB_ID('PetCareX_Optimized');

-- 1. Chuyển đường dẫn file Data
ALTER DATABASE PetCareX_Optimized
MODIFY FILE (
    NAME = 'PetCareX_Optimized', -- Tên logic (thường là PetCareX)
    FILENAME = 'D:\SQLData\PetCareX_Optimized.mdf' -- Đường dẫn mới ở ổ D
);
GO

-- 2. Chuyển đường dẫn file Log
ALTER DATABASE PetCareX_Optimized
MODIFY FILE (
    NAME = 'PetCareX_Optimized_log', -- Tên logic (thường là PetCareX_log)
    FILENAME = 'D:\SQLData\PetCareX_Optimized_log.ldf' -- Đường dẫn mới ở ổ D
);
GO

ALTER DATABASE PetCareX_Optimized SET OFFLINE WITH ROLLBACK IMMEDIATE;
GO

ALTER DATABASE PetCareX_Optimized SET ONLINE;
GO