USE PetCareX;
GO

/*USE PetCareX_Optimized;
GO*/

-- Truyền đường dẫn thư mục chứa dữ liệu vào
DECLARE @BaseFolder NVARCHAR(500) = N'D:\US\CSDL_NC\PETCAREX\'; 

ALTER TABLE PHIEUDAT NOCHECK CONSTRAINT CK_PHIEUDAT_ThoiGianDat_ThoiGianHen;
ALTER TABLE THUOC NOCHECK CONSTRAINT CK_THUOC_NSX_HSD;
ALTER TABLE VACXIN NOCHECK CONSTRAINT CK_VACXIN_NSX_HSD;
ALTER TABLE SANPHAM NOCHECK CONSTRAINT CK_SANPHAM_LoaiSP;

DELETE FROM LICHSUCONGTAC;
DELETE FROM CHITIETTOATHUOC;
DELETE FROM TOATHUOC;
DELETE FROM TIEMPHONG;
DELETE FROM KHAMBENH;
DELETE FROM DANHGIA;
DELETE FROM THONGTINTHANHTOAN;
DELETE FROM CHITIETHOADON;
DELETE FROM HOADON;
DELETE FROM LICHSUDICHVU;
DELETE FROM PHIEUDAT;
DELETE FROM THUCUNG;
DELETE FROM TAIKHOANHOIVIEN;
DELETE FROM KHACHHANG;
DELETE FROM NHANVIENQUANLY;
DELETE FROM NHANVIENBANHANG;
DELETE FROM NHANVIENTIEPTAN;
DELETE FROM BACSITHUY;
DELETE FROM NHANVIEN;
DELETE FROM VACXIN;
DELETE FROM THUOC;
DELETE FROM SANPHAM;
DELETE FROM GOITIEM;
DELETE FROM CHINHANH_DICHVU;
DELETE FROM DICHVU;
DELETE FROM CHINHANH;
DELETE FROM CAPTHANHVIEN;

DECLARE @Cmd NVARCHAR(MAX);

PRINT '>>> Loading CAPTHANHVIEN...';
SET @Cmd = N'BULK INSERT CAPTHANHVIEN FROM ''' + @BaseFolder + N'CAPTHANHVIEN\capthanhvien_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading CHINHANH...';
SET @Cmd = N'BULK INSERT CHINHANH FROM ''' + @BaseFolder + N'CHINHANH\chinhanh_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading DICHVU...';
SET @Cmd = N'BULK INSERT DICHVU FROM ''' + @BaseFolder + N'DICHVU\dichvu_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading CHINHANH_DICHVU...';
SET @Cmd = N'BULK INSERT CHINHANH_DICHVU FROM ''' + @BaseFolder + N'CHINHANH_DICHVU\chinhanh_dichvu_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading GOITIEM...';
SET @Cmd = N'BULK INSERT GOITIEM FROM ''' + @BaseFolder + N'GOITIEM\goitiem_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading SANPHAM...';
SET @Cmd = N'BULK INSERT SANPHAM FROM ''' + @BaseFolder + N'SANPHAM\sanpham_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading THUOC...';
SET @Cmd = N'BULK INSERT THUOC FROM ''' + @BaseFolder + N'THUOC\thuoc_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading VACXIN...';
SET @Cmd = N'BULK INSERT VACXIN FROM ''' + @BaseFolder + N'VACXIN\vacxin_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading NHANVIEN...';
SET @Cmd = N'BULK INSERT NHANVIEN FROM ''' + @BaseFolder + N'NHANVIEN\nhanvien_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading BACSITHUY...';
SET @Cmd = N'BULK INSERT BACSITHUY FROM ''' + @BaseFolder + N'BACSITHUY\bacsithuy_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading NHANVIENTIEPTAN...';
SET @Cmd = N'BULK INSERT NHANVIENTIEPTAN FROM ''' + @BaseFolder + N'NHANVIENTIEPTAN\nhanvientieptan_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading NHANVIENBANHANG...';
SET @Cmd = N'BULK INSERT NHANVIENBANHANG FROM ''' + @BaseFolder + N'NHANVIENBANHANG\nhanvienbanhang_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading NHANVIENQUANLY...';
SET @Cmd = N'BULK INSERT NHANVIENQUANLY FROM ''' + @BaseFolder + N'NHANVIENQUANLY\nhanvienquanly_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading LICHSUCONGTAC...';
SET @Cmd = N'BULK INSERT LICHSUCONGTAC FROM ''' + @BaseFolder + N'LICHSUCONGTAC\lichsucongtac_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading KHACHHANG...';
SET @Cmd = N'BULK INSERT KHACHHANG FROM ''' + @BaseFolder + N'KHACHHANG\khachhang_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading TAIKHOANHOIVIEN...';
SET @Cmd = N'BULK INSERT TAIKHOANHOIVIEN FROM ''' + @BaseFolder + N'TAIKHOANHOIVIEN\taikhoanhoivien_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading THUCUNG...';
SET @Cmd = N'BULK INSERT THUCUNG FROM ''' + @BaseFolder + N'THUCUNG\thucung_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading PHIEUDAT...';
SET @Cmd = N'BULK INSERT PHIEUDAT FROM ''' + @BaseFolder + N'PHIEUDAT\phieudat_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading LICHSUDICHVU...';
SET @Cmd = N'BULK INSERT LICHSUDICHVU FROM ''' + @BaseFolder + N'LICHSUDICHVU\lichsudichvu_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading HOADON...';
SET @Cmd = N'BULK INSERT HOADON FROM ''' + @BaseFolder + N'HOADON\hoadon_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading CHITIETHOADON (File lớn, vui lòng chờ)...';
SET @Cmd = N'BULK INSERT CHITIETHOADON FROM ''' + @BaseFolder + N'CHITIETHOADON\chitiethoadon_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading THONGTINTHANHTOAN...';
SET @Cmd = N'BULK INSERT THONGTINTHANHTOAN FROM ''' + @BaseFolder + N'THONGTINTHANHTOAN\thongtinthanhtoan_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading DANHGIA...';
SET @Cmd = N'BULK INSERT DANHGIA FROM ''' + @BaseFolder + N'DANHGIA\danhgia_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading KHAMBENH...';
SET @Cmd = N'BULK INSERT KHAMBENH FROM ''' + @BaseFolder + N'KHAMBENH\khambenh_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading TIEMPHONG...';
SET @Cmd = N'BULK INSERT TIEMPHONG FROM ''' + @BaseFolder + N'TIEMPHONG\tiemphong_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading TOATHUOC...';
SET @Cmd = N'BULK INSERT TOATHUOC FROM ''' + @BaseFolder + N'TOATHUOC\toathuoc_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Loading CHITIETTOATHUOC...';
SET @Cmd = N'BULK INSERT CHITIETTOATHUOC FROM ''' + @BaseFolder + N'CHITIETTOATHUOC\chitiettoathuoc_data.txt'' WITH (FIELDTERMINATOR = '','', ROWTERMINATOR = ''\n'', CODEPAGE = ''65001'');'; EXEC(@Cmd);

PRINT '>>> Re-enabling Constraints...';
ALTER TABLE PHIEUDAT CHECK CONSTRAINT CK_PHIEUDAT_ThoiGianDat_ThoiGianHen;
ALTER TABLE THUOC CHECK CONSTRAINT CK_THUOC_NSX_HSD;
ALTER TABLE VACXIN CHECK CONSTRAINT CK_VACXIN_NSX_HSD;
ALTER TABLE SANPHAM CHECK CONSTRAINT CK_SANPHAM_LoaiSP;

UPDATE HOADON
SET HOADON.TongTien = (
	SELECT SUM(CHITIETHOADON.SoLuong * CHITIETHOADON.DonGia)
	FROM CHITIETHOADON
	WHERE CHITIETHOADON.MaHD = HOADON.MaHD
)

UPDATE PHIEUDAT
SET TrangThaiPD = N'Đã xong'

PRINT '>>> FINISHED SUCCESSFULLY!';
GO

SELECT * FROM LICHSUCONGTAC;
SELECT * FROM CHITIETTOATHUOC;
SELECT * FROM TOATHUOC;
SELECT * FROM TIEMPHONG;
SELECT * FROM KHAMBENH;
SELECT * FROM DANHGIA;
SELECT * FROM THONGTINTHANHTOAN;
SELECT * FROM CHITIETHOADON;
SELECT * FROM HOADON;
SELECT * FROM LICHSUDICHVU;
SELECT * FROM PHIEUDAT;
SELECT * FROM THUCUNG;
SELECT * FROM TAIKHOANHOIVIEN;
SELECT * FROM KHACHHANG;
SELECT * FROM NHANVIENQUANLY;
SELECT * FROM NHANVIENBANHANG;
SELECT * FROM NHANVIENTIEPTAN;
SELECT * FROM BACSITHUY;
SELECT * FROM NHANVIEN;
SELECT * FROM VACXIN;
SELECT * FROM THUOC;
SELECT * FROM SANPHAM;
SELECT * FROM GOITIEM;
SELECT * FROM CHINHANH_DICHVU;
SELECT * FROM DICHVU;
SELECT * FROM CHINHANH;
SELECT * FROM CAPTHANHVIEN;